"use client";

import React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { resolveQrTokenApi } from "@/lib/api/business";
import { formatCurrency } from "@/lib/utils";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Store,
  MapPin,
  Phone,
  Clock,
  Sparkles,
  QrCode as QrIcon,
  ShieldCheck,
  ArrowRight,
  AlertCircle,
  Scissors,
  Car,
} from "lucide-react";

export default function BookByQrPage() {
  const params = useParams();
  const token = params.token as string;

  const { data, isLoading, isError } = useQuery({
    queryKey: ["qr-resolve", token],
    queryFn: () => resolveQrTokenApi(token),
    enabled: !!token,
    retry: 1,
  });

  if (isLoading) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-12 space-y-6">
        <Skeleton className="h-44 w-full rounded-3xl" />
        <div className="space-y-4">
          <Skeleton className="h-8 w-64" />
          <Skeleton className="h-5 w-48" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Skeleton className="h-32 rounded-2xl" />
          <Skeleton className="h-32 rounded-2xl" />
        </div>
      </div>
    );
  }

  if (isError || !data?.business) {
    return (
      <div className="min-h-[80vh] flex items-center justify-center p-4">
        <div className="max-w-md w-full bg-white border border-rose-100 rounded-3xl p-8 text-center shadow-xl space-y-5">
          <div className="h-16 w-16 mx-auto rounded-2xl bg-rose-50 border border-rose-200 flex items-center justify-center text-rose-600 shadow-inner">
            <AlertCircle className="h-8 w-8" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-slate-900">QR Code Expired or Invalid</h1>
            <p className="text-sm text-slate-500 mt-2 leading-relaxed">
              This QR code (<span className="font-mono text-slate-700 font-semibold">{token}</span>) is no longer active or has been regenerated by the business owner. Please scan the updated QR code displayed at the store.
            </p>
          </div>
          <div className="pt-2">
            <Link href="/dashboard">
              <Button variant="outline" className="font-semibold text-xs rounded-xl px-5 h-10">
                Back to Dashboard
              </Button>
            </Link>
          </div>
        </div>
      </div>
    );
  }

  const { business } = data;
  const isCarWash = business.businessType === "CAR_WASH";
  const services = business.services || [];

  return (
    <div className="min-h-screen bg-slate-50/50 py-10 px-4 sm:px-6">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Top Banner Card */}
        <div className="relative overflow-hidden rounded-3xl bg-linear-to-br from-slate-900 via-slate-800 to-slate-900 text-white p-6 sm:p-8 shadow-xl">
          <div className="relative z-10 space-y-4">
            <div className="flex items-center gap-2">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/10 backdrop-blur-md text-xs font-semibold text-emerald-400 border border-white/10">
                <QrIcon className="h-3.5 w-3.5" /> Scanned via Business QR
              </span>
              <span className="text-xs font-mono font-medium text-slate-400">
                #{token}
              </span>
            </div>

            <div>
              <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
                {business.name}
              </h1>
              <p className="text-slate-300 text-xs sm:text-sm mt-1 max-w-xl line-clamp-2">
                {business.description || "Welcome to our shop. Choose a service below to book an appointment or join our walk-in queue."}
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-4 text-xs text-slate-300 pt-2 border-t border-white/10">
              {business.address && (
                <span className="inline-flex items-center gap-1.5">
                  <MapPin className="h-3.5 w-3.5 text-slate-400" />
                  {business.address}, {business.city}
                </span>
              )}
              {business.phone && (
                <span className="inline-flex items-center gap-1.5">
                  <Phone className="h-3.5 w-3.5 text-slate-400" />
                  {business.phone}
                </span>
              )}
              <span className="inline-flex items-center gap-1.5 font-semibold text-emerald-400">
                <ShieldCheck className="h-3.5 w-3.5" /> Verified Business
              </span>
            </div>
          </div>

          <div className="absolute -right-6 -bottom-6 w-44 h-44 rounded-full bg-white/5 blur-2xl pointer-events-none" />
          <div className="absolute right-8 top-8 opacity-10 pointer-events-none">
            {isCarWash ? <Car className="h-32 w-32" /> : <Scissors className="h-32 w-32" />}
          </div>
        </div>

        {/* Action Header */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold text-slate-900">Select a Service to Book</h2>
            <p className="text-xs text-slate-500">Pick from our available catalogue below</p>
          </div>
          <Badge variant="neutral" className="px-3 py-1 font-medium text-xs">
            {services.length} Services Available
          </Badge>
        </div>

        {/* Services Grid */}
        {services.length === 0 ? (
          <Card className="rounded-2xl border-dashed">
            <CardContent className="p-8 text-center space-y-2">
              <Store className="h-8 w-8 text-slate-400 mx-auto" />
              <p className="text-sm font-semibold text-slate-700">No Services Available</p>
              <p className="text-xs text-slate-400">
                This business currently has no active public services. Please contact them directly.
              </p>
            </CardContent>
          </Card>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {services.map((svc: any) => (
              <Card
                key={svc.id}
                className="group rounded-2xl border border-slate-200/80 bg-white hover:border-slate-300 hover:shadow-md transition-all duration-200 flex flex-col justify-between"
              >
                <CardContent className="p-5 space-y-4">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">
                        {svc.category || "General"}
                      </span>
                      <h3 className="font-bold text-slate-900 text-base group-hover:text-primary transition-colors">
                        {svc.name}
                      </h3>
                    </div>
                    <span className="text-base font-extrabold text-slate-900 whitespace-nowrap">
                      {formatCurrency(svc.price)}
                    </span>
                  </div>

                  {svc.description && (
                    <p className="text-xs text-slate-500 line-clamp-2 leading-relaxed">
                      {svc.description}
                    </p>
                  )}

                  <div className="pt-2 border-t border-slate-100 flex items-center justify-between">
                    <span className="inline-flex items-center gap-1.5 text-xs text-slate-500 font-medium">
                      <Clock className="h-3.5 w-3.5 text-slate-400" />
                      {svc.durationMinutes || 30} mins
                    </span>

                    <Button
                      size="sm"
                      className="h-8 px-4 rounded-xl text-xs font-semibold gap-1.5"
                      onClick={() => {
                        window.location.href = `/booking?businessId=${business.id}&serviceId=${svc.id}`;
                      }}
                    >
                      <span>Book</span>
                      <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
