"use client";

import React from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { resolveQrTokenApi } from "@/lib/api/businesses";
import { formatCurrency, formatDuration } from "@/lib/utils";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { BusinessCover } from "@/components/ui/business-cover";
import { ServiceImage } from "@/components/ui/service-image";
import {
  Store,
  MapPin,
  Phone,
  Clock,
  Sparkles,
  QrCode as QrIcon,
  ShieldCheck,
  ArrowRight,
  AlertCircle,
  Scissors,
  Car,
} from "lucide-react";

export default function BookByQrPage() {
  const params = useParams();
  const router = useRouter();
  const token = params.token as string;

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["qr-resolve", token],
    queryFn: () => resolveQrTokenApi(token),
    enabled: !!token,
    retry: 1,
  });

  if (isLoading) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-12 space-y-6">
        <Skeleton className="h-44 w-full rounded-3xl" />
        <div className="space-y-4">
          <Skeleton className="h-8 w-64" />
          <Skeleton className="h-5 w-48" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Skeleton className="h-32 rounded-2xl" />
          <Skeleton className="h-32 rounded-2xl" />
        </div>
      </div>
    );
  }

  if (isError || !data?.business) {
    return (
      <div className="max-w-md mx-auto px-4 py-20 text-center space-y-5">
        <div className="h-16 w-16 mx-auto rounded-full bg-rose-50 border border-rose-200 flex items-center justify-center text-rose-600">
          <AlertCircle className="h-8 w-8" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-900">QR Code Expired or Invalid</h1>
          <p className="text-sm text-slate-500 mt-2 leading-relaxed">
            This QR code ({token}) is no longer active or has been regenerated by the business.
            Please scan the updated QR code displayed at the store.
          </p>
        </div>
        <div>
          <Link href="/">
            <Button variant="outline" className="font-semibold text-xs">
              Explore All Businesses
            </Button>
          </Link>
        </div>
      </div>
    );
  }

  const { business } = data;
  const isCarWash = business.businessType === "CAR_WASH";
  const services = business.services || [];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-8 space-y-6">
      {/* Visual Business Header Card */}
      <div className="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm">
        <BusinessCover business={business} aspectRatio="banner" className="h-48 sm:h-64" />

        <div className="p-6 sm:p-7 space-y-3">
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-200 text-xs font-bold">
              <QrIcon className="h-3.5 w-3.5 text-emerald-600" />
              Direct Storefront QR Booking
            </span>
            <span className="text-xs font-mono font-semibold text-slate-400">
              #{token}
            </span>
          </div>

          <div>
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">
              You&apos;re booking at
            </span>
            <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight mt-0.5">
              {business.name}
            </h1>
            <p className="text-slate-500 text-xs sm:text-sm mt-1 max-w-2xl leading-relaxed">
              {business.description || "Welcome! Select your service below to schedule your appointment or join the live waiting queue."}
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-y-2 gap-x-5 text-xs text-slate-500 pt-2 border-t border-slate-100 font-medium">
            {business.address && (
              <span className="inline-flex items-center gap-1.5">
                <MapPin className="h-3.5 w-3.5 text-emerald-600" />
                {business.address}, {business.city}
              </span>
            )}
            {business.phone && (
              <span className="inline-flex items-center gap-1.5">
                <Phone className="h-3.5 w-3.5 text-emerald-600" />
                {business.phone}
              </span>
            )}
            <span className="inline-flex items-center gap-1.5 font-bold text-emerald-700">
              <ShieldCheck className="h-3.5 w-3.5 text-emerald-600" /> Verified Partner
            </span>
          </div>
        </div>
      </div>

      {/* Step Roadmap */}
      <div className="bg-emerald-50/60 border border-emerald-100 rounded-2xl p-3.5 sm:p-4 flex items-center justify-around text-xs text-slate-700 font-medium">
        <span className="font-bold text-emerald-800 flex items-center gap-1.5">
          <span className="w-5 h-5 rounded-full bg-emerald-600 text-white flex items-center justify-center text-[10px]">1</span>
          Select Treatment
        </span>
        <span className="text-slate-300">→</span>
        <span className="text-slate-500 flex items-center gap-1.5">
          <span className="w-5 h-5 rounded-full bg-slate-200 text-slate-600 flex items-center justify-center text-[10px]">2</span>
          Time & Stylist
        </span>
        <span className="text-slate-300">→</span>
        <span className="text-slate-500 flex items-center gap-1.5">
          <span className="w-5 h-5 rounded-full bg-slate-200 text-slate-600 flex items-center justify-center text-[10px]">3</span>
          Instant Confirmation
        </span>
      </div>

      {/* Booking Actions & Services */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold text-slate-900 tracking-tight">
              Select a Treatment ({services.length})
            </h2>
            <p className="text-xs text-slate-500">
              Choose your service to lock in your slot with {business.name}.
            </p>
          </div>

          <Link href={`/queue?businessId=${business.id}`}>
            <Button variant="outline" size="sm" className="font-bold text-xs gap-1.5 rounded-xl cursor-pointer">
              Join Live Queue
            </Button>
          </Link>
        </div>

        {services.length === 0 ? (
          <div className="p-8 text-center text-slate-400 text-xs rounded-2xl border border-slate-200 bg-white">
            No active services currently listed for this business.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {services.map((svc) => (
              <div
                key={svc.id}
                className="p-4 rounded-2xl border border-slate-200/80 bg-white hover:border-emerald-400 hover:shadow-xs transition-all flex items-center justify-between gap-3.5 group"
              >
                <ServiceImage service={svc} size="md" />

                <div className="space-y-1 flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-bold px-2 py-0.2 rounded-full bg-emerald-50 text-emerald-700">
                      {svc.category || "Treatment"}
                    </span>
                    <span className="text-[11px] font-semibold text-slate-400 flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      {formatDuration(svc.durationMinutes)}
                    </span>
                  </div>

                  <h3 className="font-bold text-slate-900 text-sm truncate group-hover:text-emerald-700 transition-colors">
                    {svc.name}
                  </h3>

                  <p className="text-xs text-slate-500 line-clamp-1">
                    {svc.description || "Expert salon service delivered by qualified stylists."}
                  </p>
                </div>

                <div className="text-right shrink-0 space-y-1.5">
                  <div className="text-base font-extrabold text-emerald-700">
                    {formatCurrency(svc.price)}
                  </div>
                  <Link href={`/booking?businessId=${business.id}&serviceId=${svc.id}`}>
                    <Button size="sm" className="font-bold text-xs px-3.5 bg-slate-900 hover:bg-slate-800 text-white rounded-xl shadow-2xs cursor-pointer">
                      Select
                    </Button>
                  </Link>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
